FROM alpine:latest AS dovecot-builder

ARG DOVECOT_VERSION=2.4.4

RUN apk add --no-cache \
    build-base \
    curl \
    gettext-dev \
    icu-dev \
    linux-pam-dev \
    openssl-dev \
    zlib-dev

WORKDIR /build

RUN curl -fsSL "https://www.dovecot.org/releases/2.4/dovecot-${DOVECOT_VERSION}.tar.gz" \
    | tar xz \
    && cd "dovecot-${DOVECOT_VERSION}" \
    && ./configure \
      --prefix=/usr \
      --sysconfdir=/etc \
      --localstatedir=/var \
      --with-ssldir=/etc/ssl \
      --with-pam \
    && make -j"$(getconf _NPROCESSORS_ONLN)" \
    && make DESTDIR=/dovecot-root install

FROM alpine:latest

RUN apk add --no-cache lmdb postfix gettext dovecot linux-pam

COPY --from=dovecot-builder /dovecot-root/usr /usr

WORKDIR /app

COPY docker-entrypoint.sh ./docker-entrypoint.sh
COPY main.cf.template /etc/postfix/main.cf.template
COPY dovecot.conf.template /etc/dovecot/dovecot.conf.template
COPY pam.dovecot /etc/pam.d/dovecot
COPY healthcheck-container.sh ./healthcheck.sh

RUN chmod 755 ./docker-entrypoint.sh
RUN chmod 755 ./healthcheck.sh

ENTRYPOINT ["./docker-entrypoint.sh"]
