FROM alpine:latest

RUN apk add --no-cache lmdb postfix gettext

WORKDIR /app

COPY docker-entrypoint.sh ./docker-entrypoint.sh
COPY main.cf.template /etc/postfix/main.cf.template

RUN chmod 755 ./docker-entrypoint.sh

ENTRYPOINT ["./docker-entrypoint.sh"]
