#!/usr/bin/env sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
COMPOSE="${SCRIPT_DIR}/run-compose.sh"
SENDER_PASSWORD=${IMAP_HEALTHCHECK_SENDER_PASSWORD:?Set IMAP_HEALTHCHECK_SENDER_PASSWORD}
READER_PASSWORD=${IMAP_HEALTHCHECK_READER_PASSWORD:?Set IMAP_HEALTHCHECK_READER_PASSWORD}

exec "${COMPOSE}" exec -T \
  -e "IMAP_HEALTHCHECK_SENDER_PASSWORD=${SENDER_PASSWORD}" \
  -e "IMAP_HEALTHCHECK_READER_PASSWORD=${READER_PASSWORD}" \
  mail-storage /app/healthcheck.sh
